@startuml
title Menu Principal - Partida Nueva
actor Usuario
entity Cliente
entity Server
database Database

Usuario->Cliente: Iniciar Cliente
Cliente->Usuario: Pedir Credenciales

alt Login Usuario
Usuario->Cliente: Introducir Credenciales
Cliente->Server: Mandar Credenciales
Server->Database: Comprobar Credenciales
Database->Server: Comunicar Resultado
Server->Cliente: Comunicar Resultado

alt Credenciales Incorrectas
loop Mientras Incorrecto
Cliente->Usuario: Volver a pedir
Usuario->Cliente: Introducir de nuevo
Cliente->Server: Pasar credenciales
Server->Database: Comprobar
Database->Server: Comunicar resultado
Server->Cliente: Comunicar resultado
end
else Credenciales Correctas
Cliente->Usuario: Informar
end
else Entrar como Invitado
Usuario->Cliente: Login como Invitado
Cliente->Server: Comunicar Invitado
Server->Server: Asignar Invitado
Server->Cliente: Comunicar Satisfactorio
Cliente->Usuario: Informar
end

Usuario->Cliente: Boton Nueva Partida
Cliente->Usuario: Pedir Referencia Partida
Usuario->Cliente: Introducir nueva Ref.
Cliente->Server: Mandar Ref.
Server->Server: Check referencia existe.
alt Referencia existe
loop while existe
Server->Cliente: Comunicar existe
Cliente->Usuario: Volver a pedir
rnote over Usuario: Ofrecer una aleatoria.
Usuario->Cliente: Volver a introducir
Cliente->Server: Mandar
Server->Server: Comprobar de nuevo
end
else Referencia no existe
Server->Server: Juego nuevo con referencia
Server->Cliente: Comunicar todo correcto
Cliente-->Usuario: Informar
end

Cliente->Usuario: Pedir #Jugadores
Usuario->Cliente: Introducir #Jugadores
Cliente->Server: Mandar #Jugadores

Server->Cliente: Comunicar en espera de todos
Cliente-->Usuario: Informar

Cliente->Server: Esperando respuesta
Server->Server: Esperando a que se unan todos
@enduml