@startuml
title Menu Principal - Partida Nueva
actor Usuario
entity Cliente
entity Server
database Database

activate Usuario
Usuario->Cliente: Iniciar Cliente

activate Cliente
Cliente->Usuario: Pedir Credenciales
Usuario->Cliente: Boton Nueva Partida
Cliente->Usuario: Pedir Referencia Partida
Usuario->Cliente: Introducir nueva Ref.
Cliente->Server: Mandar Ref.
Server->Server: Check referencia existe.
alt Referencia existe
loop while existe
Server->Cliente: Comunicar existe
Cliente->Usuario: Volver a pedir

alt User acepta Ref. Aleatoria
Usuario->Cliente: Aceptar Aleatoria
Cliente->Server: Comunicar Aleatoria
Server->Server: Asignar Ref. Random
else Introducir Manual

Usuario->Cliente: Volver a introducir
Cliente->Server: Mandar
Server->Server: Comprobar de nuevo
end
end
else Referencia no existe
Server->Server: Juego nuevo con referencia
Server->Cliente: Comunicar todo correcto
Cliente-->Usuario: Informar
end

Cliente->Usuario: Pedir #Jugadores
Usuario->Cliente: Introducir #Jugadores
Cliente->Server: Mandar #Jugadores

Server->Cliente: Comunicar en espera de todos
Cliente-->Usuario: Informar

Cliente->Server: Esperando respuesta
Server->Server: Esperando a que se unan todos
@enduml