@startuml
title Round
entity Player1
entity Server
entity Status_thread

activate Player1
activate Server

Player1 -> Status_thread: Own Thread (Created when the game started)
activate Status_thread

Player1 -> Player1: Wait for turn; Updating Pool

Status_thread -> Server: Check (Every x seconds automatically)
Server -> Status_thread: Answer Phase, ID's turn and total pool
note right of Status_thread: (See status thread's diagram)
Status_thread --> Player1: Pass data

note over Player1: Gets turn
Player1 -> Server: Gamble / Pass
Server -> Player1: Accepted?

alt Everyone talked
    alt A bet's been done in this betting round.
     Server -> Server: Restart turn ID; Start bettings again.
    else No bet was done
        alt Phase's action done
            Server -> Server: Restart IDs; Next Phase
        else Action not done yet
            Server -> Server: Restart IDs: Do Phase's action; Round of betting
        end
    end
else Someone left
    Server -> Server: ID++; Next Player
end
@enduml