@startuml
title Menu de Usuario - Registro
entity Web
actor User
entity Cliente
database Database

activate User
activate Cliente
User->Cliente: Pedir registrarse
Cliente->Web: Abrir pagina web
activate Web

Web->User: Pedir datos
User->Web: Introducir datos

Web->Database: Check Credenciales
activate Database

alt Credenciales incorrectas
    loop Mientras Incorrecto
        Database->Web: Comunicar incorrecto
        Web->User: Volver a pedir
        rnote over User: Aqui puede salir

        User->Web: Volver a introducir
        Web->Database: Volver a comprobar
    end
else Credenciales Correctas
    Database->Web: Comunicar correcto
    Web->Database: Almacenar
    Database->Web: Resultado
    deactivate Database
    Web->User: Informar
    deactivate Web
end
@enduml