@startuml
title Menu Principal - Unirse a Partida

actor Usuario
entity Cliente
entity Server

activate Usuario
Usuario->Cliente: Iniciar Cliente
activate Cliente
Cliente->Usuario: Pedir credenciales

rnote right of Usuario: Aqui va la sección de Login común a todos.
Usuario->Cliente: Boton Unirse
Cliente->Usuario: Pedir Ref. Partida
Usuario->Cliente: Introducir Ref.
Cliente->Server: Mandar Ref.
activate Server
Server->Server: Check ref
rnote over Server: (Check en el Hashmap Interno)

alt Ref. no existe
loop while no existe
Server->Cliente: comunicar no existe
Cliente->Usuario: volver a pedir
Usuario->Cliente: volver a introducir
Cliente->Server: Mandar
Server->Server: Comprobar de nuevo
end
else Ref. existe
Server->Cliente: Comunicar existe
Cliente->Usuario: Informar
end
Cliente->Server: Esperar respuesta
rnote over Server: (Una vez todos se han unido)
Server->Cliente: Responder con comienzo
Cliente->Cliente: Pasar a ventana de juego
@enduml