/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokercliente;

import entidades.Carta;
import entidades.Jugadas;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * fixme: Hay problemas de nuevo al retirar a un Jugador. Chequear y testear.
 * Juego en Red Texas Hold'Em. Version sin limite de apuestas.
 * Ventana para Startear el juego. Cada ventana sera para un Jugador independiente.
 * Orden de uso de metodos -> this -> Jugador -> Conexion.
 * @author Mario Codes Sánchez
 * @since 09/02/2017
 * @see https://es.wikipedia.org/wiki/Texas_hold_'em
 */
public class WindowJugador extends javax.swing.JFrame {
    private static final Jugador JUGADOR = new Jugador();
    
    /**
     * Creates new form WindowJugador
     */
    public WindowJugador(String id) {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        JUGADOR.setID(id);
        this.jLabelIDJugador.setText(id);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new JPanel() {
            public void paintComponent(Graphics g) {
                Image img = Toolkit.getDefaultToolkit().getImage(
                    WindowJugador.class.getResource("/imagenes/game_menu_background2.jpg"));
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);
            }
        };
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabelPoolComun = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelIDJugador = new javax.swing.JLabel();
        jLabelJugadaPropia = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelFichasPropias = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelEstadoConexion = new javax.swing.JLabel();
        jLabelCartaMesa3 = new javax.swing.JLabel();
        jLabelCartaMesa1 = new javax.swing.JLabel();
        jLabelCartaMesa2 = new javax.swing.JLabel();
        jLabelCartaMesa4 = new javax.swing.JLabel();
        jLabelCartaPropia1 = new javax.swing.JLabel();
        jLabelCartaPropia2 = new javax.swing.JLabel();
        jLabelCartaMesa5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Game Window");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icon.png")));

        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Destapar Propias");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 409, -1, 32));

        jButton5.setText("Apostar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 409, 127, 32));

        jTextField1.setText("50");
        jTextField1.setToolTipText("");
        jPanelPrincipal.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 375, 120, -1));

        jButton4.setText("Destapar Comunes");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 409, -1, 32));

        jLabelPoolComun.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPoolComun.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPoolComun.setText("<html><b>Pool Común</b></html>");
        jPanelPrincipal.add(jLabelPoolComun, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 104, -1, 31));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        jPanelPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, -1, -1));

        jLabelIDJugador.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIDJugador.setText("ID del Jugador");
        jPanelPrincipal.add(jLabelIDJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 34, 120, 26));

        jLabelJugadaPropia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJugadaPropia.setText("Jugada Actual");
        jPanelPrincipal.add(jLabelJugadaPropia, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 121, 107, 42));

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 409, 127, 32));

        jButton2.setText("Get Ganador");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 409, 113, 32));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chicken2.png"))); // NOI18N
        jButton6.setText("Retirarse");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 409, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Conexion: ");
        jPanelPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 48, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("<html><u>Información General</u></html>");
        jLabel7.setToolTipText("");
        jPanelPrincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 6, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<html><u>Información del Jugador</u></html>");
        jPanelPrincipal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabelFichasPropias.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFichasPropias.setText("Cantidad de Fichas");
        jPanelPrincipal.add(jLabelFichasPropias, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 78, -1, 31));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chip.png"))); // NOI18N
        jPanelPrincipal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 41, 57));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chip2.png"))); // NOI18N
        jPanelPrincipal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, -1, -1));

        jLabelEstadoConexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cross.png"))); // NOI18N
        jPanelPrincipal.add(jLabelEstadoConexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 28, -1, 47));

        jLabelCartaMesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/card_back.png"))); // NOI18N
        jPanelPrincipal.add(jLabelCartaMesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, 80));

        jLabelCartaMesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/card_back.png"))); // NOI18N
        jPanelPrincipal.add(jLabelCartaMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 182, -1, 80));

        jLabelCartaMesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/card_back.png"))); // NOI18N
        jPanelPrincipal.add(jLabelCartaMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 182, -1, 80));

        jLabelCartaMesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/card_back.png"))); // NOI18N
        jPanelPrincipal.add(jLabelCartaMesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 182, -1, 80));

        jLabelCartaPropia1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/card_back.png"))); // NOI18N
        jPanelPrincipal.add(jLabelCartaPropia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 300, -1, 80));

        jLabelCartaPropia2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/card_back.png"))); // NOI18N
        jPanelPrincipal.add(jLabelCartaPropia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 300, -1, 80));

        jLabelCartaMesa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/card_back.png"))); // NOI18N
        jPanelPrincipal.add(jLabelCartaMesa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 182, -1, 80));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aces.png"))); // NOI18N
        jLabel12.setToolTipText("Jugada Actual");
        jPanelPrincipal.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 121, 39, 42));
        jPanelPrincipal.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 213, 100, 18));
        jPanelPrincipal.add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 383, -1, 8));

        jMenu1.setText("Propiedades");

        jMenuItem2.setText("Acerca De...");
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Leyenda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Obtencion de las cartas propias exclusivas del Jugador.
     */
    private void getCartasPropias() {
        if(JUGADOR.getMano().getCartasPropias().isEmpty()) {
            JUGADOR.obtenerCartasPersonales();
            JUGADOR.verCartasPropias(); //fixme: Testeo. Sout Cartas. Borrar Cuando no sea necesario.
        }else System.out.println("Ya tienes tus cartas.");
    }
    
    /**
     * Obtencion de las Cartas Comunes a todos.
     */
    private void getCartasComunes() {
        JUGADOR.obtenerCartasComunes();
        JUGADOR.verCartasComunes(); //fixme: Testeo. Sout Cartas. Borrar Cuando no sea necesario.
    }
    
    /**
     * Accion de apostar la cantidad que haya indicada.
     */
    private void apostar() {
        int pool = JUGADOR.apostar(Integer.parseInt(jTextField1.getText()));

        if(pool != -1) {
            if(pool != -2) {
                this.jLabelPoolComun.setText(Integer.toString(pool));
                this.jLabelFichasPropias.setText(Integer.toString(JUGADOR.getFichas()));
            } else  System.out.println("Obviamente no puedes apostar fichas que no tienes...");
        } else System.out.println("No es momento de apostar.");
    }
    
    private void comprobarJugada() {
        Jugadas.checkJugada(JUGADOR.getMano().getCartasPropias(), JUGADOR.getMano().getCartas_mesa());
        String jugada = Jugadas.jugada;
        this.jLabelJugadaPropia.setText(jugada);
    }
    
    private void destaparCarta(JLabel label, Carta carta) {
        String palo = carta.getPALO();
        int valor = Jugadas.getValor(carta);
        String nombreIMG = "../imagenes/" +palo +"/" +palo +valor +".png".trim();
        System.out.println("Nombre de la imagen: " +nombreIMG);
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource(nombreIMG)));
    }
    
    private void destaparPropias() {
        destaparCarta(jLabelCartaPropia1, JUGADOR.getMano().getCartasPropias().get(0));
        destaparCarta(jLabelCartaPropia2, JUGADOR.getMano().getCartasPropias().get(1));
    }
    
    private void destaparComunes() {
        int cartas = JUGADOR.getMano().getCartas_mesa().size();
        System.out.println("Cartas Length: " +cartas);
        if(cartas == 3) {
            destaparCarta(jLabelCartaMesa1, JUGADOR.getMano().getCartas_mesa().get(0));
            destaparCarta(jLabelCartaMesa2, JUGADOR.getMano().getCartas_mesa().get(1));
            destaparCarta(jLabelCartaMesa3, JUGADOR.getMano().getCartas_mesa().get(2));
        } else {
            if(cartas == 4) destaparCarta(jLabelCartaMesa4, JUGADOR.getMano().getCartas_mesa().get(3));
            else {
                if(cartas == 5) destaparCarta(jLabelCartaMesa5, JUGADOR.getMano().getCartas_mesa().get(4));
            }
        }
    }
    
    private void taparCarta(JLabel label) {
        String rutaIMG = "../imagenes/windows/juego/card_back.png";
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource(rutaIMG)));
    }
    
    private void cubrirCartas() {
        taparCarta(jLabelCartaPropia1);
        taparCarta(jLabelCartaPropia2);
        taparCarta(jLabelCartaMesa1);
        taparCarta(jLabelCartaMesa2);
        taparCarta(jLabelCartaMesa3);
        taparCarta(jLabelCartaMesa4);
        taparCarta(jLabelCartaMesa5);
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        getCartasPropias();
        comprobarJugada();
        destaparPropias();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        apostar();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        getCartasComunes();
        comprobarJugada();
        destaparComunes();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JUGADOR.enviarJugada();
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cubrirCartas();
        int ganancias = JUGADOR.getWinner();
        if(ganancias == -2) {
            JOptionPane.showMessageDialog(this, "Te has quedado sin fichas y has sido eliminado.");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jTextField1.setEnabled(false);
        }
        else {
            jLabelFichasPropias.setText(Integer.toString(ganancias));
            jLabelPoolComun.setText("");
            jLabelJugadaPropia.setText("");
            JUGADOR.finRonda();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void retirarse() {
        boolean retirado = JUGADOR.retirarse();
        if(retirado) {
            System.out.println("Jugador retirado.");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jTextField1.setEnabled(false);
        }
        else System.out.println("Problemas al retirar al jugador.");
    }
    
    private void esperarFinRonda(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
        
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jTextField1.setEnabled(true);
    }
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        retirarse();
        new Thread(() -> esperarFinRonda(evt)).start();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Conexion.cerradoCabecerasConexion();
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCartaMesa1;
    private javax.swing.JLabel jLabelCartaMesa2;
    private javax.swing.JLabel jLabelCartaMesa3;
    private javax.swing.JLabel jLabelCartaMesa4;
    private javax.swing.JLabel jLabelCartaMesa5;
    private javax.swing.JLabel jLabelCartaPropia1;
    private javax.swing.JLabel jLabelCartaPropia2;
    private javax.swing.JLabel jLabelEstadoConexion;
    private javax.swing.JLabel jLabelFichasPropias;
    private javax.swing.JLabel jLabelIDJugador;
    private javax.swing.JLabel jLabelJugadaPropia;
    private javax.swing.JLabel jLabelPoolComun;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
